services:
  postgres:
    image: postgres:15.10
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Postgres data dizinini container'ın içinde yönetmek için:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
