services:
  postgres:
    image: postgres:15.10
    container_name: bookswap
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hey-books
    ports:
      - "5432:5432"
    volumes:
      # Postgres data dizinini container'ın içinde yönetmek için:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
